import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles((theme) => ({
    root: {
        minHeight: "100vh",
        paddingBottom: "4rem",
    },
    banner: {
        width: "100%",
        height: "35vh",
        minHeight: "300px",
        position: "relative",
        backgroundSize: "cover",
        backgroundPosition: "center",
        "&::after": {
            content: '""',
            position: "absolute",
            bottom: 0,
            left: 0,
            right: 0,
            height: "50%",
            background: theme.palette.type === 'dark'
                ? "linear-gradient(to top, #0a0a0a 0%, transparent 100%)"
                : "linear-gradient(to top, #fafafa 0%, transparent 100%)",
            pointerEvents: "none",
        }
    },
    headerContainer: {
        maxWidth: "1200px",
        margin: "0 auto",
        padding: "0 2rem",
        position: "relative",
        marginTop: "-60px",
        zIndex: 2,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        textAlign: "center",
    },
    logo: {
        width: "140px",
        height: "140px",
        borderRadius: "24px",
        border: theme.palette.type === 'dark' ? "4px solid #0a0a0a" : "4px solid #fafafa",
        boxShadow: "0 8px 32px rgba(0,0,0,0.3)",
        backgroundColor: theme.palette.type === 'dark' ? "#1a1a1a" : "#ffffff",
        marginBottom: "1.5rem",
    },
    title: {
        fontFamily: "'Outfit', sans-serif",
        fontWeight: 800,
        fontSize: "2.5rem",
        color: theme.palette.type === 'dark' ? "#ffffff" : "#1a1a1a",
        display: "flex",
        alignItems: "center",
        gap: "0.5rem",
        marginBottom: "0.5rem",
    },
    verifiedIcon: {
        color: "#00BE7A",
        fontSize: "2rem",
    },
    categoryChip: {
        display: "inline-flex",
        alignItems: "center",
        padding: "3px 12px",
        borderRadius: "20px",
        fontSize: "0.78rem",
        fontWeight: 700,
        fontFamily: "'Inter', sans-serif",
        letterSpacing: "0.04em",
        textTransform: "uppercase",
        background: "linear-gradient(135deg, rgba(123,97,255,0.18) 0%, rgba(0,190,122,0.14) 100%)",
        border: "1px solid rgba(123,97,255,0.3)",
        color: "#7B61FF",
        marginBottom: "0.75rem",
    },
    description: {
        maxWidth: "600px",
        color: theme.palette.type === 'dark' ? "var(--text-muted)" : "rgba(0,0,0,0.7)",
        fontFamily: "'Inter', sans-serif",
        fontSize: "1rem",
        lineHeight: 1.6,
        marginBottom: "1rem",
    },
    socialRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "0.75rem",
        marginBottom: "1.5rem",
        flexWrap: "wrap",
    },
    socialLink: {
        display: "inline-flex",
        alignItems: "center",
        gap: "0.35rem",
        padding: "5px 12px",
        borderRadius: 8,
        fontSize: "0.82rem",
        fontWeight: 600,
        fontFamily: "'Inter', sans-serif",
        textDecoration: "none",
        background: theme.palette.type === 'dark' ? "var(--glass-bg-hover)" : "rgba(0,0,0,0.05)",
        border: theme.palette.type === 'dark' ? "1px solid var(--glass-border)" : "1px solid rgba(0,0,0,0.08)",
        color: theme.palette.type === 'dark' ? "var(--text-muted)" : "rgba(0,0,0,0.65)",
        transition: "all 0.2s ease",
        "&:hover": {
            background: "rgba(123,97,255,0.12)",
            borderColor: "rgba(123,97,255,0.4)",
            color: "#7B61FF",
        },
    },
    statsContainer: {
        display: "flex",
        gap: "3rem",
        flexWrap: "wrap",
        justifyContent: "center",
        padding: "1.5rem 2rem",
        background: theme.palette.type === 'dark' ? "var(--glass-bg)" : "var(--glass-bg)",
        backdropFilter: "blur(12px)",
        borderRadius: "20px",
        border: theme.palette.type === 'dark' ? "1px solid var(--glass-bg)" : "1px solid rgba(0, 0, 0, 0.05)",
        boxShadow: theme.palette.type === 'dark' ? "0 8px 32px rgba(0,0,0,0.3)" : "0 8px 32px rgba(0,0,0,0.05)",
        marginBottom: "3rem",
    },
    statBox: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
    },
    statValue: {
        fontFamily: "'Outfit', sans-serif",
        fontWeight: 800,
        fontSize: "1.5rem",
        color: theme.palette.type === 'dark' ? "#ffffff" : "#1a1a1a",
        display: "flex",
        alignItems: "center",
        gap: "0.3rem",
    },
    statLabel: {
        fontFamily: "'Inter', sans-serif",
        fontSize: "0.85rem",
        textTransform: "uppercase",
        letterSpacing: "0.05em",
        fontWeight: 600,
        color: theme.palette.type === 'dark' ? "var(--text-muted)" : "rgba(0,0,0,0.5)",
        marginTop: "0.2rem",
    },
    ethIcon: {
        fontSize: "1.2rem",
        color: theme.palette.type === 'dark' ? "var(--text-muted)" : "rgba(0,0,0,0.7)",
    },
    gridContainer: {
        maxWidth: "1400px",
        margin: "0 auto",
        padding: "0 2rem",
    },
    gridHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: "1.5rem",
        flexWrap: "wrap",
        gap: "1rem",
    },
    tabsRow: {
        display: "flex",
        alignItems: "center",
        gap: "0.25rem",
        borderBottom: theme.palette.type === 'dark' ? "1px solid var(--glass-bg-hover)" : "1px solid rgba(0,0,0,0.08)",
        marginBottom: "2rem",
    },
    tabBtn: {
        padding: "0.6rem 1.4rem",
        borderRadius: "8px 8px 0 0",
        background: "transparent",
        border: "none",
        cursor: "pointer",
        fontFamily: "'Outfit', sans-serif",
        fontWeight: 700,
        fontSize: "1rem",
        color: theme.palette.type === 'dark' ? "var(--text-muted)" : "rgba(0,0,0,0.45)",
        borderBottom: "3px solid transparent",
        marginBottom: "-1px",
        transition: "all 0.2s",
    },
    tabBtnActive: {
        color: theme.palette.type === 'dark' ? "#ffffff" : "#1a1a1a",
        borderBottom: "3px solid #7B61FF",
    },
    filterBar: {
        display: "flex",
        alignItems: "center",
        gap: "0.75rem",
        marginBottom: "1.75rem",
        flexWrap: "wrap",
    },
    filterSelect: {
        padding: "7px 14px",
        borderRadius: 8,
        background: theme.palette.type === 'dark' ? "var(--glass-bg-hover)" : "rgba(0,0,0,0.05)",
        border: theme.palette.type === 'dark' ? "1px solid var(--glass-border)" : "1px solid rgba(0,0,0,0.1)",
        color: theme.palette.type === 'dark' ? "#ffffff" : "#1a1a1a",
        fontFamily: "'Inter', sans-serif",
        fontSize: "0.85rem",
        fontWeight: 600,
        cursor: "pointer",
        outline: "none",
    },
    filterChip: {
        padding: "6px 14px",
        borderRadius: 20,
        background: "transparent",
        border: theme.palette.type === 'dark' ? "1px solid var(--glass-bg-active)" : "1px solid rgba(0,0,0,0.1)",
        color: theme.palette.type === 'dark' ? "var(--text-muted)" : "rgba(0,0,0,0.55)",
        fontFamily: "'Inter', sans-serif",
        fontSize: "0.82rem",
        fontWeight: 600,
        cursor: "pointer",
        transition: "all 0.2s",
    },
    filterChipActive: {
        background: "rgba(123,97,255,0.15)",
        border: "1px solid rgba(123,97,255,0.45)",
        color: "#7B61FF",
    },
    activityTable: {
        width: "100%",
        borderCollapse: "collapse",
        fontFamily: "'Inter', sans-serif",
    },
    activityTh: {
        textAlign: "left",
        padding: "0.6rem 1rem",
        fontSize: "0.78rem",
        textTransform: "uppercase",
        letterSpacing: "0.06em",
        fontWeight: 700,
        color: theme.palette.type === 'dark' ? "var(--text-muted)" : "rgba(0,0,0,0.4)",
        borderBottom: theme.palette.type === 'dark' ? "1px solid var(--glass-bg-hover)" : "1px solid rgba(0,0,0,0.07)",
    },
    activityTd: {
        padding: "0.75rem 1rem",
        fontSize: "0.9rem",
        color: theme.palette.type === 'dark' ? "var(--text-muted)" : "rgba(0,0,0,0.75)",
        borderBottom: theme.palette.type === 'dark' ? "1px solid var(--glass-bg)" : "1px solid rgba(0,0,0,0.04)",
        verticalAlign: "middle",
    },
    ownerActions: {
        display: "flex",
        alignItems: "center",
        gap: "0.5rem",
        flexWrap: "wrap",
    },
    snackbar: {
        position: "fixed",
        bottom: "1.5rem",
        left: "50%",
        transform: "translateX(-50%)",
        background: "linear-gradient(135deg, #7B61FF, #00BE7A)",
        color: "white",
        padding: "0.6rem 1.5rem",
        borderRadius: 30,
        fontFamily: "'Inter', sans-serif",
        fontWeight: 700,
        fontSize: "0.9rem",
        boxShadow: "0 8px 24px rgba(0,0,0,0.3)",
        zIndex: 9999,
        animation: "$fadeIn 0.3s ease",
        display: "flex",
        alignItems: "center",
        gap: "0.5rem",
    },
    "@keyframes fadeIn": {
        from: { opacity: 0, transform: "translateX(-50%) translateY(20px)" },
        to: { opacity: 1, transform: "translateX(-50%) translateY(0)" },
    },
}));

export { useStyles };
